version: '3.8'

services:
  postgres:
    container_name: nest-ednb-postgres-container
    image: 'bitnami/postgresql:latest'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest-ednb
      PGDATA: /data/bitnami/postgresql
    volumes:
      - ./data/pg:/bitnami/postgresql
    user: root

  cache:
    container_name: nest-ednb-cache-container
    image: 'bitnami/redis:latest'
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./data/redis:/data